farma/urls.py
from django.contrib import admin
from django.urls import path, include
from authentication.views import Login

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", Login.as_view(), name="login"),
    path("farma/", include(("pachaqtecfarma.urls", "farma"))),
]

pachaqtecfarma/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Client(models.Model):
    id = models.AutoField(primary_key=True)
    dni = models.CharField(max_length=15, unique=True, null=False)
    name = models.CharField(max_length=50, blank=False, null=False)
    last_name = models.CharField(max_length=50, blank=False, null=False)
    points = models.FloatField(default=0)

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering = ["dni"]

    def __str__(self):
        return self.name


class Product(models.Model):
    id = models.AutoField(primary_key=True)
    product = models.CharField(max_length=100, blank=False, null=False)
    stock = models.IntegerField(blank=False, null=False)
    price = models.FloatField(blank=False, null=False)

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        ordering = ["product"]

    def __str__(self):
        return self.product


class Invoice(models.Model):
    id = models.AutoField(primary_key=True)
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    fecha = models.DateField(null=True, blank=True, default=timezone.now)
    products = models.ManyToManyField(Product, through="Resume")
    total = models.FloatField(default=0)

    class Meta:
        verbose_name = "Factura"
        verbose_name_plural = "Facturas"
        ordering = ["id"]

    def __str__(self):
        return (
            "Factura "
            + str(self.id)
            + " - "
            + self.client.name
            + " "
            + self.client.last_name
        )


class Resume(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(blank=False, null=False)

    class Meta:
        verbose_name = "Resumen"
        verbose_name_plural = "Resumenes"
        ordering = ["product"]

    def __str__(self):
        return f"Resumen {self.invoice} - {self.product} - {self.quantity} u."

templates/base-login.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="shortcut icon" href="{% static 'static/assets/images/favicon.ico' %}">
    <!-- App css -->
    <link href="{% static 'static/assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'static/assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'static/assets/css/app.min.css' %}" rel="stylesheet" type="text/css" />

    <title>{% block title %} {% endblock %}</title>


    {% block css %} {% endblock %}
</head>

<body class="authentication-bg authentication-bg-pattern">

    <!-- Navigation Bar-->
    <header id="topnav">

        <!-- Topbar Start -->
        <div class="navbar-custom">
            <div class="container-fluid">
                <ul class="list-unstyled topnav-menu float-right mb-0">

                    <li class="dropdown notification-list">
                        <!-- Mobile menu toggle-->
                        <a class="navbar-toggle nav-link">
                            <div class="lines">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </a>
                        <!-- End mobile menu toggle-->
                    </li>


                    <li class="dropdown notification-list">


                        <span class="pro-user-name ml-1">
                            {{user.username}} - <a href="{%url 'farma:logout' %}">Cerrar Sesión</a>
                        </span>


                    </li>

                </ul>

            </div> <!-- end container-fluid-->
        </div>
        <!-- end Topbar -->

        <div class="topbar-menu">
            <div class="container-fluid">
                <div id="navigation">
                    <!-- Navigation Menu-->
                    <ul class="navigation-menu">

                        <li class="has-submenu">
                            <a href="#">
                                <i class="fe-airplay"></i>Opciones <div class="arrow-down"></div></a>
                            <ul class="submenu">
                                <li>
                                    <a href="{% url 'farma:list.product'%}">Listar Productos</a>
                                </li>

                                <li>
                                    <a href="{% url 'farma:list.invoices'%}">Listar Facturas</a>
                                </li>

                                <li>
                                    <a href="{% url 'farma:create_invoice'%}">Crear Factura</a>
                                </li>

                            </ul>
                        </li>

                    </ul>
                    <!-- End navigation menu -->

                    <div class="clearfix"></div>
                </div>
                <!-- end #navigation -->
            </div>
            <!-- end container -->
        </div>
        <!-- end navbar-custom -->

    </header>
    <!-- End Navigation Bar-->

    {% block content %} {% endblock %}

    {% block js %} {% endblock %}
</body>

</html>

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="shortcut icon" href="{% static 'static/assets/images/favicon.ico' %}">
    <!-- App css -->
    <link href="{% static 'static/assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'static/assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'static/assets/css/app.min.css' %}" rel="stylesheet" type="text/css" />

    <title>{% block title %} {% endblock %}</title>


    {% block css %} {% endblock %}
</head>

<body class="authentication-bg authentication-bg-pattern">
    {% block content %} {% endblock %}

    {% block js %} {% endblock %}
</body>

</html>

templates/cliente.html
{% extends 'base.html' %}
{% load static %}

{% block title%} Detalle de cliente {%endblock %}
{% block content %}

<body>
    <!-- ============================================================== -->
    <!-- Start Page Content here -->
    <!-- ============================================================== -->

    <div class="wrapper">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <h4 class="page-title">Detalle de cliente {{cliente.name}} {{cliente.last_name}} </h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row">
                <div class="col-12">
                    <div class="card-box">
                        <div class="row">
                            <div class="col-xl-12">
                                <div class="pl-xl-3 mt-3 mt-xl-0">
                                    <a href="#" class="text-primary">{{cliente.dni}}</a>
                                    <h4 class="mb-3">{{cliente.name}} {{cliente.last_name}}</h4>
                                    <h4 class="mb-4">Puntos : <b>{{cliente.points}}</b></h4>
                                    <!--                                        <h4><span class="badge bg-soft-success text-success mb-4">Instock</span></h4> -->
                                </div>
                            </div> <!-- end col -->
                        </div>
                        <!-- end row -->


                        <div class="table-responsive mt-4">
                            <h4 class="mb-4">Compras:</h4>
                            <table class="table table-bordered table-centered mb-0">
                                <thead class="thead-light">
                                    <tr>
                                        <th>Id</th>
                                        <th>Fecha</th>
                                        <th>Productos</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {%for factura in facturas%}
                                    <tr>
                                        <td>{{factura.id}}</td>
                                        <td>{{factura.fecha}}</td>
                                        <td>
                                            <!--     <div class="progress-w-percent mb-0">
                                                    <span class="progress-value">478 </span>
                                                    <div class="progress progress-sm">
                                                        <div class="progress-bar bg-success" role="progressbar" style="width: 56%;" aria-valuenow="56" aria-valuemin="0" aria-valuemax="100"></div>
                                                    </div>
                                                </div> -->
                                            {%for producto in factura.resume_set.all%}
                                            <p>{{producto.product}}</p>
                                            {%endfor%}
                                        </td>
                                    </tr>
                                    {%endfor%}
                                </tbody>
                            </table>
                        </div>

                    </div> <!-- end card-->
                </div> <!-- end col-->
            </div>
            <!-- end row-->

        </div> <!-- end container -->
    </div>
    <!-- end wrapper -->

    <!-- ============================================================== -->
    <!-- End Page content -->
    <!-- ============================================================== -->

    {%endblock%}

    <!-- Vendor js -->
    <script src="assets/js/vendor.min.js"></script>

    <!-- App js-->
    <script src="assets/js/app.min.js"></script>

</body>

templates/listar-facturas.html
{% extends 'base-login.html' %}


{% block content %}
<div class="wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h3 class="one">Listado</h3>
                <p style="color:#ffffff; font-size:16px;">Haga click sobre el ID para ver el detalle</p>
            </div>
        </div>
        <table class="table">
            <style>
                tbody,
                thead,
                h3 {
                    color: white;
                }
            </style>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>FECHA</th>
                    <th>TOTAL</th>
                </tr>
            </thead>
            <tbody>
                {% for factura in facturas %}
                <tr>
                    <td><a style="color:#ffffff; font-size:16px;"
                            href="./ver-factura/{{factura.id}}">{{ factura.id }}</a></td>
                    <td>{{ factura.fecha }}</td>
                    <td>{{ factura.total }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/producto-agregado.html
{% extends 'base.html' %}
{% load static %}

{% block title%} Verificación Cliente {%endblock %}
{% block content %}

<body class="authentication-bg authentication-bg-pattern">

    <div class="account-pages mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-pattern">

                        <div class="card-body p-4">

                            <div class="text-center w-75 m-auto">
                                <a href="index.html">
                                    <span><img src="assets/images/logo-dark.png" alt="" height="22"></span>
                                </a>
                                <p class="text-muted mb-4 mt-3">{{Mensaje}}</p>
                            </div>
                            <div class="form-group mb-0 text-center">
                                <a class="btn btn-info btn-block" href="../llenar-factura/{{id}}"> Agregar Otro </a>
                            </div>
                            <br>

                            <div class="form-group mb-0 text-center">
                                <a class="btn btn-info btn-block" href="../cerrar-factura/{{id}}"> Finalizar </a>
                            </div>


                        </div> <!-- end card-body -->
                    </div>
                    <!-- end card -->
                    <!-- end row -->

                </div> <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- end page -->
    {%endblock%}

    <footer class="footer footer-alt">
        2015 - 2019 &copy; UBold theme by <a href="" class="text-white-50">Coderthemes</a>
    </footer>

    <!-- Vendor js -->
    <script src="{% static 'static/assets/js/vendor.min.js' %}"></script>

    <!-- App js -->
    <script src="{% static 'static/assets/js/app.min.js' %}"></script>
</body>

templates/ver-factura.html
{% extends 'base-login.html' %}
{% load static %}

{% block title%} Detalle de cliente {%endblock %}
{% block content %}

<body>
    <!-- ============================================================== -->
    <!-- Start Page Content here -->
    <!-- ============================================================== -->

    <div class="wrapper">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <a class="btn btn-warning" href="../ver-facturas">Volver al listado</a>
                    <div class="page-title-box">
                        <h4 class="page-title">Detalle de factura</h4>

                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row">
                <div class="col-12">
                    <div class="card-box">
                        <div class="row">
                            <div class="col-xl-12">
                                <div class="pl-xl-3 mt-3 mt-xl-0">
                                    <a href="#" class="text-primary">{{factura.id}}</a>
                                    <h4 class="mb-3">Cliente: {{factura.client.name}} {{factura.client.last_name}}</h4>
                                    <h4 class="mb-4">Total : <b>{{factura.total}}</b></h4>
                                    <!--                                        <h4><span class="badge bg-soft-success text-success mb-4">Instock</span></h4> -->
                                </div>
                            </div> <!-- end col -->
                        </div>
                        <!-- end row -->


                        <div class="table-responsive mt-4">
                            <h4 class="mb-4">Productos:</h4>
                            <table class="table table-bordered table-centered mb-0">
                                <thead class="thead-light">
                                    <tr>
                                        <th>Producto</th>
                                        <th>Precio</th>
                                        <th>Cantidad</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {%for entry in factura.resume_set.all%}
                                    <tr>
                                        <td>{{entry.product}}</td>
                                        <td>{{entry.product.price}}</td>
                                        <td>{{entry.quantity}}</td>
                                    </tr>
                                    {%endfor%}
                                </tbody>
                            </table>
                        </div>

                    </div> <!-- end card-->
                </div> <!-- end col-->
            </div>
            <!-- end row-->

        </div> <!-- end container -->
    </div>
    <!-- end wrapper -->

    <!-- ============================================================== -->
    <!-- End Page content -->
    <!-- ============================================================== -->

    {%endblock%}
    <!-- Footer Start -->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    2015 - 2019 &copy; UBold theme by <a href="">Coderthemes</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- end Footer -->



    <!-- Vendor js -->
    <script src="assets/js/vendor.min.js"></script>

    <!-- App js-->
    <script src="assets/js/app.min.js"></script>

</body>